package vista.PanelesAdmin;

import java.awt.Color;
 
import Controladores.ControlUser;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Edwis Jimenez
 */
public class PanelUsuariosAdmin extends javax.swing.JPanel {
    
    public static void main(String[] args) {
        javax.swing.JFrame frame = new javax.swing.JFrame("Prueba");
        frame.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
        frame.add(new PanelUsuariosAdmin());
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }

    /**
     * Creates new form PanelVuelosAdmin
     */
    public PanelUsuariosAdmin() {
        initComponents();
        
        // Asignar imagenes a los iconos svg
        sVGEditar.setSvgImage("vista/imagenes/pen-svgrepo-com.svg", 14, 14);
        sVGEliminar.setSvgImage("vista/imagenes/delete-filled-svgrepo-com.svg", 14, 14);
        
        // Configuracion de elementos
        btnBuscar.setArc(10);
        
        btnNuevo.setArc(10);
        btnNuevo.setBackground(new Color(7, 122, 61, 255));
        
        btnEditar.setArc(10);
        
        btnEliminar.setArc(10);
        btnEliminar.setBackground(new Color(204, 65, 56, 255));
       new ControlUser(this);
    }
    
    //Getters y Setters
    public JTable getTblUsuarios() {
        return tblUsuarios;
    }
 
    public swing.Button getBtnNuevo() {
        return btnNuevo;
    }
 
    public swing.Button getBtnEditar() {
        return btnEditar;
    }
 
    public swing.Button getBtnEliminar() {
        return btnEliminar;
    }
 
    public swing.Button getBtnBuscar() {
        return btnBuscar;
    }
 
    public JTextField getTxtBuscar() {
        return txtBuscar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        sVGEliminar = new swing.SVGImage();
        btnBuscar = new swing.Button();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        sVGEditar = new swing.SVGImage();
        btnEditar = new swing.Button();
        btnNuevo = new swing.Button();
        btnEliminar = new swing.Button();

        setBackground(new java.awt.Color(214, 221, 230));
        setMinimumSize(new java.awt.Dimension(470, 510));
        setPreferredSize(new java.awt.Dimension(701, 547));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Buscar:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 12, -1, -1));
        add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 6, 357, 35));
        add(sVGEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 507, 20, 20));

        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);
        add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 7, 124, -1));

        tblUsuarios.setBackground(new java.awt.Color(244, 245, 249));
        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Usuario", "Nombre", "Pasaporte", "Correo ", "Numero_Telefono"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblUsuarios);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 53, 701, 436));
        add(sVGEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 507, 20, 20));

        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setText("    Editar");
        btnEditar.setToolTipText("");
        add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 501, 100, -1));

        btnNuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(this::btnNuevoActionPerformed);
        add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(592, 7, 103, -1));

        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("     Eliminar");
        btnEliminar.setToolTipText("");
        add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 501, 100, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.Button btnBuscar;
    private swing.Button btnEditar;
    private swing.Button btnEliminar;
    private swing.Button btnNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private swing.SVGImage sVGEditar;
    private swing.SVGImage sVGEliminar;
    private javax.swing.JTable tblUsuarios;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
