package vista;

import java.awt.Color;

/**
 *
 * @author RAVEN
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        System.out.println(getClass().getClassLoader().getResource("vista/imagenes/AstraFlyLogo.svg"));
        sVGImageUser.setSvgImage("vista/imagenes/user-svgrepo-com.svg", 25, 25);
        sVGImageLock.setSvgImage("vista/imagenes/lock-svgrepo-com.svg", 25, 25);
        sVGAstraFlyIcon.setSvgImage("vista/imagenes/AstraFlyIconInSVG(1).svg", 200, 150);
        //setBackground(new Color(0, 0, 0, 0));

        background.setLayout(null);
        //jPanel1.setSize(jPanel1.getPreferredSize());

        background.addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(java.awt.event.ComponentEvent e) {
                centrarPanel();
            }
        });

        centrarPanel();
    }

    private void centrarPanel() {
        int x = (background.getWidth() - jPanel1.getWidth()) / 2;
        int y = (background.getHeight() - jPanel1.getHeight()) / 2;
        jPanel1.setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new login.Background();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textField1 = new swing.TextField();
        passwordField1 = new swing.PasswordField();
        button1 = new swing.Button();
        jLabel6 = new javax.swing.JLabel();
        sVGImageLock = new swing.SVGImage();
        sVGAstraFlyIcon = new swing.SVGImage();
        sVGImageUser = new swing.SVGImage();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBlur(jPanel1);
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bienvenido");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(197, 205, 232));
        jLabel2.setText("Inicia sesión para continuar");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        textField1.setHint("Usuario");
        textField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField1ActionPerformed(evt);
            }
        });
        jPanel1.add(textField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 240, -1));

        passwordField1.setHint("Contraseña");
        jPanel1.add(passwordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 240, -1));

        button1.setBackground(new java.awt.Color(4, 103, 232));
        button1.setForeground(new java.awt.Color(255, 255, 255));
        button1.setText("Iniciar Sesión");
        button1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel1.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 200, 40));

        jLabel6.setForeground(new java.awt.Color(170, 184, 191));
        jLabel6.setText("¿No tienes cuenta? Contacta con el administrador");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 290, 40));
        jPanel1.add(sVGImageLock, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 30, 30));
        jPanel1.add(sVGAstraFlyIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 167, 80));
        jPanel1.add(sVGImageUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 30, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("AstraFly");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 110, 50));

        background.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 330, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 754, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLoginActionPerformed
        //String user = txtUser.getText();
        //String pass = String.valueOf(txtPassword.getPassword());
    }//GEN-LAST:event_cmdLoginActionPerformed

    private void textField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private login.Background background;
    private swing.Button button1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private swing.PasswordField passwordField1;
    private swing.SVGImage sVGAstraFlyIcon;
    private swing.SVGImage sVGImageLock;
    private swing.SVGImage sVGImageUser;
    private swing.TextField textField1;
    // End of variables declaration//GEN-END:variables
}
